version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python dependencies"
      - pip install -r requirements.txt -t ./package

  build:
    commands:
      - echo "Packaging Lambda function"
      - cp -r src/* package/
      - cd package
      - zip -r ../deployment.zip .

artifacts:
  files:
    - deployment.zip
