version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - cd src
      - zip -r ../deployment.zip .

artifacts:
  files:
    - deployment.zip
