version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      pip install --target ./package -r requirements.txt

  build:
    commands:
      cp lambda_function.py package/
      cd package
      zip -r ../function.zip .
      cd ..

artifacts:
  files:
    - function.zip
