version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies to ./package"
      - pip install --target ./package -r requirements.txt

  build:
    commands:
      - echo "Copying lambda_function.py into package directory"
      - cp lambda_function.py package/
      - echo "Zipping code into function.zip"
      - cd package
      - zip -r ../function.zip .
      - cd ..
      - echo "Build phase done"

artifacts:
  files:
    - function.zip
