version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Build phase done. No manual zipping.

artifacts:
  files:
    - lambda_function.py
    - requirements.txt
    - '**/*'
