version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      pip install --target . -r requirements.txt
      
  build:
    commands:
      zip -r function.zip .

artifacts:
  files:
    - function.zip
